branch-defaults:
  default:
    environment: entertainweb-test
global:
  application_name: EntertainWeb
  branch: null
  default_ec2_keyname: EntertainWeb-key
  default_platform: Python 3.4
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
