# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # initial = True
    #
    # dependencies = [
    # ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(default='', max_length=20)),
                ('message_string', models.CharField(default='', max_length=595)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ButtonDivider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divider_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='button',
            name='parent_divider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lights.ButtonDivider'),
        ),
    ]
