# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import lights.models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0003_auto_20170816_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('token', models.IntegerField(default=lights.models.unique_random_num, max_length=4, primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField()),
                ('in_use', models.BooleanField(default=False)),
            ],
        ),
    ]
