# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import lights.models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0004_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.IntegerField(default=lights.models.unique_random_num, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
