# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0005_auto_20170816_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 16, 22, 31, 58, 338503, tzinfo=utc)),
        ),
    ]
