# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0006_auto_20170816_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='secret_key',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 17, 6, 20, 23, 404945, tzinfo=utc)),
        ),
    ]
