# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import lights.models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0007_auto_20170817_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expiry_date',
            field=models.DateTimeField(default=lights.models.now_plus_some),
        ),
    ]
