# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0008_auto_20170817_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='secret_key',
        ),
    ]
