# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0009_remove_accesstoken_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='notes',
            field=models.CharField(default='', max_length=512),
        ),
    ]
